language: python
python:
 - "3.6"

install:
  - pip3 install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov
script:
  - python -m py.test --cov=firstfood.py
after_success:
  - coveralls
